import React from 'react';
import { ShieldCheck, Lock, Eye, FileCheck, Server, AlertTriangle, Key, HeartPulse, UserCheck, HardDrive } from 'lucide-react';

export const SecuritySection: React.FC = () => {
  const securityPillars = [
    {
      title: 'Encryption in transit & at rest',
      desc: 'AES-256 and TLS 1.3 encryption protocols safeguard patient dialogues and clinical records across all layers.',
      icon: <Lock className="w-5 h-5 text-[#20D6C7]" />
    },
    {
      title: 'Role-based access controls (RBAC)',
      desc: 'Granular access policies ensure doctors, nurses, front-desk staff, and TPA billing agents see only relevant data.',
      icon: <Key className="w-5 h-5 text-[#53CFFF]" />
    },
    {
      title: 'Immutable audit trails',
      desc: 'Comprehensive system logs record every AI transcription, document edit, doctor approval, and data export.',
      icon: <Eye className="w-5 h-5 text-[#6BE7B7]" />
    },
    {
      title: 'Consent-aware workflows',
      desc: 'Explicit patient consent collection before voice call recording or WhatsApp messaging initiation.',
      icon: <FileCheck className="w-5 h-5 text-[#8B7CFF]" />
    },
    {
      title: 'Configurable data retention',
      desc: 'Hospitals define custom data purge timelines to align with institutional privacy policies.',
      icon: <HardDrive className="w-5 h-5 text-[#20D6C7]" />
    },
    {
      title: 'Human-in-the-loop governance',
      desc: 'All clinical outputs require mandatory doctor verification before entering official HIS records.',
      icon: <UserCheck className="w-5 h-5 text-[#53CFFF]" />
    },
    {
      title: 'Deployment flexibility',
      desc: 'Designed to support cloud, hybrid, or private hospital network deployment architectures.',
      icon: <Server className="w-5 h-5 text-[#6BE7B7]" />
    },
    {
      title: 'Healthcare data protection readiness',
      desc: 'Architected to align with strict Indian healthcare data privacy principles and hospital IT standards.',
      icon: <ShieldCheck className="w-5 h-5 text-[#8B7CFF]" />
    }
  ];

  return (
    <section id="security" className="py-24 relative bg-[#040d14] border-t border-[#20D6C7]/15 overflow-hidden">
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#09242A] border border-[#20D6C7]/30 text-xs font-semibold text-[#20D6C7]">
            <ShieldCheck className="w-3.5 h-3.5" /> Responsible Healthcare AI
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-heading font-extrabold text-white tracking-tight leading-tight">
            Healthcare AI <br />
            <span className="text-gradient">built around trust.</span>
          </h2>
          <p className="text-slate-400 text-base sm:text-lg">
            Security, clinical safety, and data sovereignty are embedded into every component of the ACQSA architecture.
          </p>
        </div>

        {/* Security Pillars Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {securityPillars.map((sp, idx) => (
            <div
              key={idx}
              className="p-6 rounded-2xl glass-panel glass-panel-hover flex flex-col gap-3 group"
            >
              <div className="w-10 h-10 rounded-xl bg-[#09242A] border border-[#20D6C7]/30 flex items-center justify-center group-hover:scale-110 transition-transform">
                {sp.icon}
              </div>
              <h3 className="font-heading font-bold text-base text-white group-hover:text-[#20D6C7] transition-colors">
                {sp.title}
              </h3>
              <p className="text-xs text-slate-400 leading-relaxed font-normal">
                {sp.desc}
              </p>
            </div>
          ))}
        </div>

        {/* Responsible AI & Medical Emergency Mandatory Notice Box */}
        <div className="max-w-4xl mx-auto bg-[#09242A] border-2 border-[#53CFFF]/40 rounded-3xl p-6 sm:p-8 shadow-2xl space-y-4">
          <div className="flex items-center gap-3 border-b border-white/10 pb-3">
            <HeartPulse className="w-6 h-6 text-[#53CFFF] shrink-0" />
            <h3 className="font-heading font-bold text-lg text-white">
              Clinical Responsibility & Medical Disclaimer
            </h3>
          </div>

          <p className="text-sm text-slate-200 leading-relaxed">
            <strong>ACQSA AI assists authorized hospital teams.</strong> It does not replace doctors, independently diagnose patients or provide emergency medical treatment. All clinical documentation and summaries generated by ACQSA AI require mandatory review and sign-off by a licensed healthcare professional.
          </p>

          <div className="p-3.5 rounded-xl bg-[#071621] border border-[#20D6C7]/30 text-xs text-[#20D6C7] font-semibold flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-[#20D6C7] shrink-0" />
            <span>
              For a medical emergency, contact the hospital directly or call local emergency medical services immediately.
            </span>
          </div>
        </div>

      </div>
    </section>
  );
};
